
# parsetab.py
# This file is automatically generated. Do not edit.
_tabversion = '3.2'

_lr_method = 'LALR'

_lr_signature = '|F\x12V\xa6=}\x10b\xff\x87u\\\xa8-:'
    
_lr_action_items = {'COMMENT':([0,1,2,3,4,5,6,7,8,10,11,12,],[-1,2,-9,-8,-4,-2,-5,-3,-7,2,-6,-10,]),'FALSE':([0,1,2,3,4,5,6,7,8,10,11,12,],[-1,3,-9,-8,-4,-2,-5,-3,-7,3,-6,-10,]),'STRING':([0,1,2,3,4,5,6,7,8,10,11,12,],[-1,4,-9,-8,-4,-2,-5,-3,-7,4,-6,-10,]),'NUMBER':([0,1,2,3,4,5,6,7,8,9,10,11,12,],[-1,6,-9,-8,-4,-2,-5,-3,-7,11,6,-6,-10,]),'EQUALS':([7,],[10,]),'IDENTIFIER':([0,1,2,3,4,5,6,7,8,10,11,12,],[-1,7,-9,-8,-4,-2,-5,-3,-7,7,-6,-10,]),'TRUE':([0,1,2,3,4,5,6,7,8,10,11,12,],[-1,8,-9,-8,-4,-2,-5,-3,-7,8,-6,-10,]),'DOT':([6,],[9,]),'$end':([0,1,2,3,4,5,6,7,8,11,12,],[-1,0,-9,-8,-4,-2,-5,-3,-7,-6,-10,]),}

_lr_action = { }
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = { }
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'expr':([1,10,],[5,12,]),'explist':([0,],[1,]),}

_lr_goto = { }
for _k, _v in _lr_goto_items.items():
   for _x,_y in zip(_v[0],_v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = { }
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> explist","S'",1,None,None,None),
  ('explist -> <empty>','explist',0,'p_explist','glacierParser.py',20),
  ('explist -> explist expr','explist',2,'p_explist','glacierParser.py',21),
  ('expr -> IDENTIFIER','expr',1,'p_identifier','glacierParser.py',29),
  ('expr -> STRING','expr',1,'p_string','glacierParser.py',33),
  ('expr -> NUMBER','expr',1,'p_number','glacierParser.py',37),
  ('expr -> NUMBER DOT NUMBER','expr',3,'p_number','glacierParser.py',38),
  ('expr -> TRUE','expr',1,'p_bool','glacierParser.py',46),
  ('expr -> FALSE','expr',1,'p_bool','glacierParser.py',47),
  ('expr -> COMMENT','expr',1,'p_comment','glacierParser.py',51),
  ('expr -> IDENTIFIER EQUALS expr','expr',3,'p_assign','glacierParser.py',55),
]
